### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by sajattack** [k0kubun/tetris#9]
My game crashed:
```panic: bytes.Buffer: truncation out of range
goroutine 1 [running]:
bytes.(*Buffer).Truncate(0x563920, 0x0)
	/usr/lib/go/src/bytes/buffer.go:74 +0xc1
bytes.(*Buffer).WriteTo(0x563920, 0x54f500, 0xc42000e028, 0x7f2b641eb070, 0x563920, 0x1)
	/usr/lib/go/src/bytes/buffer.go:228 +0x5b
io.copyBuffer(0x54f500, 0xc42000e028, 0x54f400, 0x563920, 0x0, 0x0, 0x0, 0xc42003ce00, 0x1, 0x1)
	/usr/lib/go/src/io/io.go:380 +0x31a
io.Copy(0x54f500, 0xc42000e028, 0x54f400, 0x563920, 0x1, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:360 +0x68
github.com/k0kubun/termbox-go.flush(0x20, 0x1)
	/home/paul/go/src/github.com/k0kubun/termbox-go/termbox.go:160 +0x55
github.com/k0kubun/termbox-go.Flush(0xc42022e680, 0xc6)
	/home/paul/go/src/github.com/k0kubun/termbox-go/api.go:189 +0x1a2
main.rewriteScreen(0x4ec0c8)
	/home/paul/go/src/github.com/k0kubun/tetris/view.go:89 +0xab
main.refreshScreen()
	/home/paul/go/src/github.com/k0kubun/tetris/view.go:77 +0x2d
main.waitKeyInput()
	/home/paul/go/src/github.com/k0kubun/tetris/keybind.go:46 +0x104
main.main()
	/home/paul/go/src/github.com/k0kubun/tetris/tetris.go:148 +0xfb
```

**Comment by k0kubun** [comment]
Thank you for reporting. Do you have some reproduction steps? It's hard to debug if we don't have them.

**Comment by sajattack** [comment]
Haven't been able to repro just got to like 10k and it crashed.

**Comment by sajattack** [comment]
I'm also having the game freeze when animating out some blocks.

**Comment by sajattack** [comment]
When run with race detector:
```==================
WARNING: DATA RACE
Write at 0x0000006072b0 by goroutine 9:
  github.com/k0kubun/termbox-go.Clear()
      /home/paul/go/src/github.com/k0kubun/termbox-go/api.go:272 +0x3e
  main.rewriteScreen()
      /home/paul/go/src/github.com/k0kubun/tetris/view.go:81 +0x3a
  main.refreshScreen()
      /home/paul/go/src/github.com/k0kubun/tetris/view.go:77 +0x3a
  main.main.func1()
      /home/paul/go/src/github.com/k0kubun/tetris/tetris.go:133 +0x4f
  main.(*Clock).start.func1()
      /home/paul/go/src/github.com/k0kubun/tetris/clock.go:36 +0x190

Previous write at 0x0000006072b0 by main goroutine:
  github.com/k0kubun/termbox-go.Close()
      /home/paul/go/src/github.com/k0kubun/termbox-go/api.go:138 +0x569
  main.main()
      /home/paul/go/src/github.com/k0kubun/tetris/tetris.go:149 +0x20c

Goroutine 9 (running) created at:
  main.(*Clock).start()
      /home/paul/go/src/github.com/k0kubun/tetris/clock.go:41 +0xc3
  main.main()
      /home/paul/go/src/github.com/k0kubun/tetris/tetris.go:147 +0x206
```

**Comment by MichaelS11** [comment]
If interested, refactored and bug fixed code here:

https://github.com/MichaelS11/tetris
